
               
    <div class="form-login">
    <form method="POST" name = "register_form" action="/auth/register">
    <div class="form-group">
        <input name="user_name" class="form-control" type="text" placeholder="Логин" required>
    </div>
    <div class="form-group">
        <input name="user_email" class="form-control" type="email" placeholder="Email" required>
    </div>
    <div class="form-group">
        <input name="user_password" class="form-control" type="password" placeholder="Пароль" required>
    </div>
    <div class="form-group">     
        <input name="user_password_repeat" class="form-control" type="password" placeholder="Повторите пароль" required>
    </div>
    <div class="form-group">     
    <input name="user_role" type="radio" value="advertiser"> Рекламодатель
    <input name="user_role" type="radio" value="webmaster" checked> Вебмастер
</div>
    <hr>
      
    <input name="register" class ="btn btn-primary" type="submit" value="Зарегистрироваться">
 
  
    
 
      </form> 
         
    </div>
