<footer class="footer">
    <div class="footer_info">

    
        <div class="contacts"></div>
        <div class="main-content">
        <h3 class="mt-3 ml-20">Контакты</h3>
        <ul class="list">
            <li class="first">Tel: <a href="tel: +12345678910">+12345678910</a></li>
            <li>github: <a href="https://github.com/tatvsam">TatVSam</a></li>
            <li class="last">email: <a href="mailto:info@adtech.host">info@adtech.host</a></li>
        </ul>
</div>

</footer>